
services:
  web:
    container_name: fastapi_catalog
    build: .
    command: bash -c "./wait-for-it.sh postgres:5432 -- ./wait-for-it.sh redis:6379 -- uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    working_dir: /code
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  postgres:
    image: postgres:15.3-alpine
    container_name: postgresql
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local